databases:
  - name: postgres
    databaseName: railstarter_production
    user: postgres

services:
  - type: web
    name: railstarter
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: railstarter
          property: connectionString
      - key: ffff6f9fcf58028daed9b083b24ec2d7
        sync: false