production:
  cloud_name: dubl5onvo
  api_key: 769113622111229
  api_secret: Hn9u7sxsnGC-x0-C8uVARBZGKEE
  enhance_image_tag: true
  static_file_support: false
  cdn_subdomain: true

  development:
  cloud_name: dubl5onvo
  api_key: 769113622111229
  api_secret: Hn9u7sxsnGC-x0-C8uVARBZGKEE
  enhance_image_tag: true
  static_file_support: false
  cdn_subdomain: true